/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#1e2022",
        "surface-container-lowest": "#0c0e10",
        "on-surface-variant": "#c7c4d7",
        surface: "#121416",
        "on-primary": "#1000a9",
        "surface-tint": "#c0c1ff",
        "secondary-container": "#3626ce",
        "on-tertiary": "#4f2500",
        "on-secondary": "#1d00a5",
        "on-error": "#690005",
        "inverse-surface": "#e2e2e5",
        "surface-variant": "#333537",
        "inverse-on-surface": "#2f3133",
        "on-primary-fixed": "#07006c",
        tertiary: "#ffb783",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "surface-bright": "#38393b",
        "on-background": "#e2e2e5",
        "surface-container-low": "#1a1c1e",
        "on-tertiary-container": "#452000",
        "surface-container-highest": "#333537",
        "on-surface": "#e2e2e5",
        "secondary-fixed-dim": "#c3c0ff",
        "inverse-primary": "#494bd6",
        "outline-variant": "#464554",
        "on-primary-container": "#0d0096",
        "tertiary-fixed-dim": "#ffb783",
        "primary-container": "#8083ff",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-error-container": "#ffdad6",
        secondary: "#c3c0ff",
        "on-secondary-fixed-variant": "#3323cc",
        "surface-container-high": "#282a2c",
        "tertiary-fixed": "#ffdcc5",
        "on-tertiary-fixed-variant": "#703700",
        "primary-fixed-dim": "#c0c1ff",
        outline: "#908fa0",
        "on-tertiary-fixed": "#301400",
        "surface-dim": "#121416",
        primary: "#c0c1ff",
        "secondary-fixed": "#e2dfff",
        "on-secondary-container": "#b3b1ff",
        background: "#121416",
        "on-secondary-fixed": "#0f0069",
        "tertiary-container": "#d97721",
        "primary-fixed": "#e1e0ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.375rem",
        gutter: "0.75rem",
        "space-lg": "1rem",
        "space-md": "0.75rem",
        margin: "1rem",
        "space-xl": "1.5rem",
      },
      fontFamily: {
        "headline-xl": ["var(--font-geist)", "Geist", "sans-serif"],
        "mono-md": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "mono-lg": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "body-sm": ["var(--font-geist)", "Geist", "sans-serif"],
        "headline-md": ["var(--font-geist)", "Geist", "sans-serif"],
        "body-md": ["var(--font-geist)", "Geist", "sans-serif"],
        "headline-xl-mobile": ["var(--font-geist)", "Geist", "sans-serif"],
        "label-sm": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "headline-sm": ["var(--font-geist)", "Geist", "sans-serif"],
        "headline-lg": ["var(--font-geist)", "Geist", "sans-serif"],
        "body-lg": ["var(--font-geist)", "Geist", "sans-serif"],
        "label-md": ["var(--font-geist)", "Geist", "sans-serif"],
        "headline-lg-mobile": ["var(--font-geist)", "Geist", "sans-serif"],
        "mono-sm": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-xl": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.025em", fontWeight: "600" }],
        "mono-md": ["0.8125rem", { lineHeight: "1.25rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "mono-lg": ["0.875rem", { lineHeight: "1.375rem", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-sm": ["0.75rem", { lineHeight: "1.125rem", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.015em", fontWeight: "500" }],
        "body-md": ["0.8125rem", { lineHeight: "1.25rem", letterSpacing: "0", fontWeight: "400" }],
        "headline-xl-mobile": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["0.625rem", { lineHeight: "0.875rem", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-sm": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-lg": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["0.9375rem", { lineHeight: "1.5rem", letterSpacing: "0", fontWeight: "400" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "mono-sm": ["0.6875rem", { lineHeight: "1rem", letterSpacing: "0", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
