import { Simulation } from "./simulation/types";

export const MOCK_SIMULATIONS: Simulation[] = [
  {
    id: "BT-1042",
    repo: "ShopLite",
    branch: "main",
    commit: "7f9a2e1",
    proposedChange: {
      title: "Rename users.email → users.email_address",
      targetFile: "prisma/schema.prisma",
      findPattern: "email String @unique",
      findLineStart: 42,
      findLineEnd: 44,
      replacePattern: "email_address String @unique",
      oldCode: "model User {\n  email String @unique\n  posts Post[]\n}",
      newCode: "model User {\n  email_address String @unique\n  posts Post[]\n}",
    },
    status: "regression",
    statusLabel: "4 Workflows Broken",
    testsPassed: 8,
    totalTests: 12,
    duration: "1m 42s",
    timeAgo: "2 min ago",
    workspaces: "Acme Infra / Prod-Sim",
    workflows: [
      {
        id: "wf-1",
        name: "Authentication Engine",
        filePath: "src/auth/auth.ts",
        line: 42,
        state: "FAILED",
        count: 2,
        observedFailure: "Deprecated field: users.email",
        details: "loginWithCredentials(), jwtVerify()",
        suggestedFix: "Map to email_address",
      },
      {
        id: "wf-2",
        name: "User Profile Service",
        filePath: "src/profile/profile.ts",
        line: 118,
        state: "FAILED",
        count: 1,
        observedFailure: "DTO expects email field",
        details: "fetchUserProfile()",
        suggestedFix: "Synchronize DTO mapping",
      },
      {
        id: "wf-3",
        name: "Order Dispatch",
        filePath: "src/services/email-service.ts",
        line: 89,
        state: "FAILED",
        count: 1,
        observedFailure: "Property `email` does not exist",
        details: "sendOrderReceipt()",
        suggestedFix: "Add compatible accessor",
      },
      {
        id: "wf-4",
        name: "Admin Reporting",
        filePath: "src/admin/customers.ts",
        line: 204,
        state: "FAILED",
        count: 2,
        observedFailure: "Customer email field is undefined",
        details: "exportCustomerCsv()",
        suggestedFix: "Update projection",
      },
      {
        id: "wf-5",
        name: "Checkout & Payments",
        filePath: "src/orders/orders.ts",
        line: 55,
        state: "PASSED",
        count: 4,
        observedFailure: "No direct dependency",
        details: "processCheckout(), stripeWebhook()",
        suggestedFix: "No change required",
      },
    ],
    stackTrace: `FAIL src/services/email-service.test.ts > sendOrderReceipt
  TypeError: Property 'email' does not exist on type 'User'. Did you mean 'email_address'?
    at sendOrderReceipt (src/services/email-service.ts:94:21)
    at Object.<anonymous> (tests/integration/orders.spec.ts:14:11)
  Simulated Twin Latency: 14ms | Memory: 41.2MB | Context: Node.js v20.11`,
    remediation: {
      planSummary:
        "Bob identified 4 affected call sites and generated a backward-compatible remediation plan.",
      preparedDiff: {
        added: 18,
        removed: 6,
        files: [
          { status: "M", path: "prisma/schema.prisma", type: "secondary" },
          { status: "M", path: "src/auth/auth.ts", type: "primary" },
          { status: "M", path: "src/services/email-service.ts", type: "primary" },
          { status: "M", path: "src/admin/customers.ts", type: "primary" },
        ],
      },
      targetState: "12 / 12 workflows passed — Safe to deploy.",
    },
    bobRemediationData: {
      summary: "Rename users.email to users.email_address causes 4 downstream workflow regressions across auth, profile, email-service, and admin reporting.",
      affectedFiles: [
        "prisma/schema.prisma",
        "src/auth/auth.ts",
        "src/profile/profile.ts",
        "src/services/email-service.ts",
        "src/admin/customers.ts"
      ],
      plan: [
        "Trace broken call sites expecting 'email' property on User model.",
        "Implement backward-compatible accessor or virtual field for 'email' pointing to 'email_address'.",
        "Update consumers to use 'email_address' progressively while preventing runtime breaks.",
        "Run verification test suite in isolated sandbox."
      ],
      proposedChanges: [
        {
          filePath: "src/auth/auth.ts",
          description: "Support both 'email' and 'email_address' in auth payload mapping.",
        },
        {
          filePath: "src/services/email-service.ts",
          description: "Add backward-compatible getter for user.email.",
        },
        {
          filePath: "src/admin/customers.ts",
          description: "Project both fields in customer export.",
        },
      ],
      tests: ["npm test"],
    },
    hostEnv: {
      sandboxStatus: "Active",
      repoTag: "ShopLite@main",
      filesChanged: 1,
      testSuite: "npm test",
      productionImpact: "0 (Isolated)",
    },
  },
  {
    id: "BT-1041",
    repo: "ShopLite",
    branch: "feature/checkout",
    commit: "3d2e19a",
    proposedChange: {
      title: "Update order status enum",
      targetFile: "apps/checkout/types.ts",
      findPattern: "type OrderStatus = 'PENDING' | 'PAID'",
      findLineStart: 12,
      findLineEnd: 15,
      replacePattern: "type OrderStatus = 'PENDING' | 'PROCESSING' | 'PAID'",
      oldCode: "export type OrderStatus = 'PENDING' | 'PAID' | 'FAILED';",
      newCode: "export type OrderStatus = 'PENDING' | 'PROCESSING' | 'PAID' | 'FAILED';",
    },
    status: "safe",
    statusLabel: "Safe / Verified",
    testsPassed: 24,
    totalTests: 24,
    duration: "2m 11s",
    timeAgo: "18 min ago",
    workspaces: "Acme Infra / Prod-Sim",
    workflows: [
      {
        id: "wf-1",
        name: "Order Processing Service",
        filePath: "apps/checkout/processor.ts",
        line: 34,
        state: "PASSED",
        count: 14,
        observedFailure: "No regression detected",
        details: "handleStatusTransition()",
        suggestedFix: "No change required",
      },
      {
        id: "wf-2",
        name: "Webhook Dispatcher",
        filePath: "apps/checkout/webhooks.ts",
        line: 88,
        state: "PASSED",
        count: 10,
        observedFailure: "No regression detected",
        details: "dispatchOrderEvent()",
        suggestedFix: "No change required",
      },
    ],
    stackTrace: `PASS apps/checkout/processor.test.ts (24 tests passed)
  Simulated Twin Latency: 9ms | Memory: 38.4MB | Context: Node.js v20.11`,
    remediation: {
      planSummary: "No remediation required. All assertions passed cleanly.",
      preparedDiff: {
        added: 2,
        removed: 1,
        files: [{ status: "M", path: "apps/checkout/types.ts", type: "secondary" }],
      },
      targetState: "24 / 24 workflows passed — Safe to deploy.",
    },
    hostEnv: {
      sandboxStatus: "Standby",
      repoTag: "ShopLite@feature/checkout",
      filesChanged: 1,
      testSuite: "npm test",
      productionImpact: "0 (Isolated)",
    },
  },
  {
    id: "BT-1040",
    repo: "Inventory API",
    branch: "v2-sync",
    commit: "8c12b7f",
    proposedChange: {
      title: "Add warehouse_id to payload",
      targetFile: "proto/v2/inventory.proto",
      findPattern: "string item_id = 1;",
      findLineStart: 25,
      findLineEnd: 28,
      replacePattern: "string item_id = 1;\n  string warehouse_id = 2;",
      oldCode: "message StockItem {\n  string item_id = 1;\n}",
      newCode: "message StockItem {\n  string item_id = 1;\n  string warehouse_id = 2;\n}",
    },
    status: "safe",
    statusLabel: "Safe / Verified",
    testsPassed: 31,
    totalTests: 31,
    duration: "1m 05s",
    timeAgo: "1 hour ago",
    workspaces: "Acme Infra / Prod-Sim",
    workflows: [],
    stackTrace: `PASS tests/inventory.spec.ts (31 tests passed)
  Simulated Twin Latency: 11ms | Memory: 29.8MB | Context: Node.js v20.11`,
    remediation: {
      planSummary: "All protobuf schema consumers validated with backward compatibility.",
      preparedDiff: {
        added: 1,
        removed: 0,
        files: [{ status: "M", path: "proto/v2/inventory.proto", type: "secondary" }],
      },
      targetState: "31 / 31 workflows passed — Safe to deploy.",
    },
    hostEnv: {
      sandboxStatus: "Standby",
      repoTag: "Inventory API@v2-sync",
      filesChanged: 1,
      testSuite: "npm test",
      productionImpact: "0 (Isolated)",
    },
  },
  {
    id: "BT-1039",
    repo: "Billing Worker",
    branch: "stripe-v12",
    commit: "45a90d1",
    proposedChange: {
      title: "Deprecate charge.create webhook",
      targetFile: "services/worker/stripe.go",
      findPattern: "case 'charge.created':",
      findLineStart: 104,
      findLineEnd: 110,
      replacePattern: "case 'payment_intent.succeeded':",
      oldCode: "case 'charge.created':\n  handleCharge(ctx, event)",
      newCode: "case 'payment_intent.succeeded':\n  handlePaymentIntent(ctx, event)",
    },
    status: "needs_attention",
    statusLabel: "Needs attention",
    testsPassed: 14,
    totalTests: 19,
    duration: "3m 15s",
    timeAgo: "3 hours ago",
    workspaces: "Acme Infra / Prod-Sim",
    workflows: [],
    stackTrace: `FAIL services/worker/stripe_test.go
  Error: legacy legacy_customer_billing test failed
  Simulated Twin Latency: 22ms | Memory: 52.1MB | Context: Go 1.22`,
    remediation: {
      planSummary: "Dual webhook listener shim generated to prevent billing dropoffs.",
      preparedDiff: {
        added: 12,
        removed: 4,
        files: [{ status: "M", path: "services/worker/stripe.go", type: "primary" }],
      },
      targetState: "19 / 19 workflows passed — Safe to deploy.",
    },
    hostEnv: {
      sandboxStatus: "Standby",
      repoTag: "Billing Worker@stripe-v12",
      filesChanged: 1,
      testSuite: "go test ./...",
      productionImpact: "0 (Isolated)",
    },
  },
  {
    id: "BT-1038",
    repo: "Auth Gateway",
    branch: "session-jwt",
    commit: "22ef88c",
    proposedChange: {
      title: "Rotate RS256 key validator",
      targetFile: "internal/security/jwt.rs",
      findPattern: "verify_legacy_rs256()",
      findLineStart: 88,
      findLineEnd: 92,
      replacePattern: "verify_jwks_cached()",
      oldCode: "verify_legacy_rs256(token)",
      newCode: "verify_jwks_cached(token)",
    },
    status: "safe",
    statusLabel: "Safe / Verified",
    testsPassed: 42,
    totalTests: 42,
    duration: "2m 45s",
    timeAgo: "5 hours ago",
    workspaces: "Acme Infra / Prod-Sim",
    workflows: [],
    stackTrace: `PASS internal/security/jwt_test.rs (42 tests passed)
  Simulated Twin Latency: 6ms | Memory: 19.3MB | Context: Rust 1.77`,
    remediation: {
      planSummary: "Key rotation verified against simulated legacy session tokens.",
      preparedDiff: {
        added: 4,
        removed: 2,
        files: [{ status: "M", path: "internal/security/jwt.rs", type: "secondary" }],
      },
      targetState: "42 / 42 workflows passed — Safe to deploy.",
    },
    hostEnv: {
      sandboxStatus: "Standby",
      repoTag: "Auth Gateway@session-jwt",
      filesChanged: 1,
      testSuite: "cargo test",
      productionImpact: "0 (Isolated)",
    },
  },
];
